# Generated by Django 5.0.4 on 2026-10-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('receipt_header', models.TextField(blank=True)),
                ('receipt_footer', models.TextField(blank=True)),
                ('currency_code', models.CharField(default='KGS', max_length=3)),
                ('currency_symbol', models.CharField(default='сом', max_length=12)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('default_language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian')], default='uz', max_length=2)),
                ('timezone', models.CharField(default='Asia/Bishkek', max_length=64)),
                ('sale_counter', models.PositiveIntegerField(default=0)),
                ('receipt_counter', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
