# Generated by Django 5.0.4 on 2026-09-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name'], 'verbose_name': 'Vendor', 'verbose_name_plural': 'Vendors'},
        ),
        migrations.AlterModelOptions(
            name='vendortransaction',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Vendor transaction', 'verbose_name_plural': 'Vendor transactions'},
        ),
    ]
