# Generated by Django 5.0.4 on 2026-10-01 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '__first__'),
        ('vendors', '0002_alter_vendor_options_alter_vendortransaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stores.store'),
        ),
    ]
