# Generated by Django 5.0.4 on 2026-10-01 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_alter_color_options_and_more'),
        ('stores', '__first__'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_name_d2210c_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='product_var_product_b96575_idx',
        ),
        migrations.AlterUniqueTogether(
            name='size',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stores.store'),
        ),
        migrations.AddField(
            model_name='color',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stores.store'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stores.store'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stores.store'),
        ),
        migrations.AddField(
            model_name='size',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stores.store'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='size',
            unique_together={('store', 'name', 'size_type')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'is_active', 'name'], name='products_store_i_b53886_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['store', 'product', 'is_active'], name='product_var_store_i_9701be_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='category_store_name'),
        ),
        migrations.AddConstraint(
            model_name='color',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='color_store_name'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('store', 'barcode'), name='product_store_barcode'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('store', 'barcode'), name='variant_store_barcode'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('store', 'sku'), name='variant_store_sku'),
        ),
    ]
