# Generated by Django 5.0.4 on 2026-10-01 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_backfill_legacy'),
        ('products', '0003_remove_product_products_name_d2210c_idx_and_more'),
        ('stores', '0002_backfill_legacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.store'),
        ),
        migrations.AlterField(
            model_name='color',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.store'),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.store'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.store'),
        ),
        migrations.AlterField(
            model_name='size',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.store'),
        ),
    ]
