# Generated by Django 5.0.4 on 2026-09-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('login', 'Login'), ('login_failed', 'Failed login'), ('logout', 'Logout'), ('user_created', 'User created'), ('user_updated', 'User updated'), ('user_deactivated', 'User deactivated'), ('pin_changed', 'PIN changed'), ('product_created', 'Product created'), ('product_updated', 'Product updated'), ('product_deleted', 'Product deleted'), ('price_changed', 'Price changed'), ('category_changed', 'Category changed'), ('stock_receipt', 'Stock receipt'), ('stock_adjusted', 'Stock adjusted'), ('inventory_count', 'Inventory count'), ('sale_created', 'Sale created'), ('sale_returned', 'Sale returned'), ('expense_created', 'Expense created'), ('income_created', 'Income created'), ('finance_deleted', 'Finance entry deleted'), ('settings_changed', 'Settings changed')], db_index=True, max_length=40)),
                ('entity', models.CharField(blank=True, max_length=50)),
                ('entity_id', models.CharField(blank=True, max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
