"""Django Forms / ModelForms for the server-rendered UI.

Replaces the JSON payloads the SPA used to send: every write now goes through a
validated form with a CSRF token.
"""
from decimal import Decimal

from django import forms

from apps.authentication.models import User
from apps.finance.models import FinanceEntry
from apps.products.models import Category, Product, ProductVariant

# Shown when a scanned/typed barcode is already used by another product or
# variant in the same store (DB enforces product_store_barcode / variant_store_barcode).
DUPLICATE_BARCODE_MSG = ('Bu shtrih kod allaqachon boshqa tovarda mavjud — boshqa kod kiriting '
                         'yoki "Avto" tugmasini bosing. (Этот штрих-код уже используется другим '
                         'товаром — введите другой.)')


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'description', 'is_active']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'input'}),
            'description': forms.Textarea(attrs={'class': 'textarea', 'rows': 3}),
        }


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'category', 'barcode', 'image', 'base_cost_price',
                  'base_selling_price', 'low_stock_threshold', 'description', 'is_active']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'input'}),
            'category': forms.Select(attrs={'class': 'select'}),
            'barcode': forms.TextInput(attrs={'class': 'input'}),
            'base_cost_price': forms.NumberInput(attrs={'class': 'input', 'step': '0.01'}),
            'base_selling_price': forms.NumberInput(attrs={'class': 'input', 'step': '0.01'}),
            'low_stock_threshold': forms.NumberInput(attrs={'class': 'input'}),
            'description': forms.Textarea(attrs={'class': 'textarea', 'rows': 3}),
        }

    def __init__(self, *args, store=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.store = store
        if store is not None:
            self.fields['category'].queryset = Category.objects.filter(store=store, is_active=True)
        self.fields['category'].required = False
        self.fields['image'].required = False
        # Empty barcode is auto-generated by the view (the "Avto" button fills
        # it client-side; scanners/typers may skip it entirely).
        self.fields['barcode'].required = False
        # The template hides the cost column from managers; the form must not
        # fail for them - the owner can set the cost later.
        self.fields['base_cost_price'].required = False
        self.fields['low_stock_threshold'].required = False

    def clean_base_cost_price(self):
        value = self.cleaned_data.get('base_cost_price')
        return value if value not in (None, '') else Decimal('0')

    def clean_low_stock_threshold(self):
        value = self.cleaned_data.get('low_stock_threshold')
        return value if value not in (None, '') else 5

    def clean_barcode(self):
        """Per-store barcode uniqueness: a friendly form error instead of a 500
        from the product_store_barcode constraint on save."""
        barcode = (self.cleaned_data.get('barcode') or '').strip()
        if not barcode or self.store is None:
            return barcode
        qs = Product.objects.filter(store=self.store, barcode=barcode)
        if self.instance.pk:
            qs = qs.exclude(pk=self.instance.pk)
        if qs.exists():
            raise forms.ValidationError(DUPLICATE_BARCODE_MSG)
        return barcode


class VariantForm(forms.ModelForm):
    """One product variant row (colour × size)."""

    class Meta:
        model = ProductVariant
        fields = ['id', 'color', 'size', 'barcode', 'selling_price', 'cost_price',
                  'stock_quantity', 'low_stock_threshold', 'is_active']
        widgets = {
            'color': forms.Select(attrs={'class': 'select'}),
            'size': forms.Select(attrs={'class': 'select'}),
            'barcode': forms.TextInput(attrs={'class': 'input'}),
            'selling_price': forms.NumberInput(attrs={'class': 'input', 'step': '0.01'}),
            'cost_price': forms.NumberInput(attrs={'class': 'input', 'step': '0.01'}),
            'stock_quantity': forms.NumberInput(attrs={'class': 'input'}),
            'low_stock_threshold': forms.NumberInput(attrs={'class': 'input'}),
        }

    def __init__(self, *args, store=None, product=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.store = store
        from apps.products.models import Color, Size
        if store is not None:
            self.fields['color'].queryset = Color.objects.filter(store=store)
            self.fields['size'].queryset = Size.objects.filter(store=store)
        for name in ('color', 'size', 'selling_price', 'cost_price'):
            self.fields[name].required = False
        # Variant barcodes are optional: the view auto-generates them when empty.
        self.fields['barcode'].required = False
        # The variant table has no threshold column; fall back to the model default.
        self.fields['low_stock_threshold'].required = False

    def clean_low_stock_threshold(self):
        value = self.cleaned_data.get('low_stock_threshold')
        return value if value not in (None, '') else 5

    def clean_barcode(self):
        """Same guard as ProductForm: variant_store_barcode must not blow up
        with a 500 when a scanned barcode is already taken in this store."""
        barcode = (self.cleaned_data.get('barcode') or '').strip()
        if not barcode or self.store is None:
            return barcode
        qs = ProductVariant.objects.filter(store=self.store, barcode=barcode)
        if self.instance.pk:
            qs = qs.exclude(pk=self.instance.pk)
        if qs.exists():
            raise forms.ValidationError(DUPLICATE_BARCODE_MSG)
        return barcode


class VariantFormSetBase(forms.BaseInlineFormSet):
    """Cross-row guard: two visible rows of one formset may not share a barcode
    (each row alone passes its DB check, then the second INSERT would 500)."""

    def clean(self):
        super().clean()
        seen = set()
        for form in self.forms:
            if not getattr(form, 'cleaned_data', None) or form.cleaned_data.get('DELETE'):
                continue
            code = (form.cleaned_data.get('barcode') or '').strip()
            if not code:
                continue
            if code in seen:
                raise forms.ValidationError(DUPLICATE_BARCODE_MSG)
            seen.add(code)


class FinanceForm(forms.ModelForm):
    amount = forms.DecimalField(
        min_value=Decimal('0.01'), max_digits=15, decimal_places=2,
        widget=forms.NumberInput(attrs={'class': 'input', 'step': '0.01', 'min': '0'}))

    class Meta:
        model = FinanceEntry
        fields = ['entry_type', 'amount', 'category', 'entry_date', 'comment']
        widgets = {
            'entry_type': forms.Select(attrs={'class': 'select'}),
            'amount': forms.NumberInput(attrs={'class': 'input', 'step': '0.01', 'min': '0'}),
            'category': forms.TextInput(attrs={'class': 'input'}),
            'entry_date': forms.DateInput(attrs={'class': 'input', 'type': 'date'}),
            'comment': forms.Textarea(attrs={'class': 'textarea', 'rows': 2}),
        }


class EmployeeForm(forms.ModelForm):
    pin = forms.CharField(required=False, max_length=8,
                          widget=forms.TextInput(attrs={'class': 'input', 'inputmode': 'numeric',
                                                        'autocomplete': 'off'}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'phone', 'role', 'language', 'is_active']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'input'}),
            'last_name': forms.TextInput(attrs={'class': 'input'}),
            'username': forms.TextInput(attrs={'class': 'input'}),
            'phone': forms.TextInput(attrs={'class': 'input'}),
            'role': forms.Select(attrs={'class': 'select'}),
            'language': forms.Select(attrs={'class': 'select'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['role'].choices = [('manager', 'Manager'), ('cashier', 'Cashier')]
        if self.instance.pk:
            self.fields['username'].disabled = True

    def clean_pin(self):
        pin = self.cleaned_data.get('pin') or ''
        if pin and (not pin.isdigit() or not (4 <= len(pin) <= 8)):
            raise forms.ValidationError('PIN 4-8 raqamdan iborat bo‘lishi kerak.')
        return pin


class StoreSettingsForm(forms.Form):
    """Store-level settings (receipt header/footer, thresholds)."""
    receipt_header = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'textarea', 'rows': 2}))
    receipt_footer = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'textarea', 'rows': 2}))
    low_stock_threshold = forms.IntegerField(min_value=0, widget=forms.NumberInput(attrs={'class': 'input'}))
    phone = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'input'}))
    address = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'textarea', 'rows': 2}))
