"""Django Forms / ModelForms for the server-rendered UI.

Replaces the JSON payloads the SPA used to send: every write now goes through a
validated form with a CSRF token.
"""
from decimal import Decimal

from django import forms

from apps.authentication.models import User
from apps.finance.models import FinanceEntry
from apps.products.models import Category, Product, ProductVariant


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'description', 'is_active']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'input'}),
            'description': forms.Textarea(attrs={'class': 'textarea', 'rows': 3}),
        }


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'category', 'barcode', 'image', 'base_cost_price',
                  'base_selling_price', 'low_stock_threshold', 'description', 'is_active']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'input'}),
            'category': forms.Select(attrs={'class': 'select'}),
            'barcode': forms.TextInput(attrs={'class': 'input'}),
            'base_cost_price': forms.NumberInput(attrs={'class': 'input', 'step': '0.01'}),
            'base_selling_price': forms.NumberInput(attrs={'class': 'input', 'step': '0.01'}),
            'low_stock_threshold': forms.NumberInput(attrs={'class': 'input'}),
            'description': forms.Textarea(attrs={'class': 'textarea', 'rows': 3}),
        }

    def __init__(self, *args, store=None, **kwargs):
        super().__init__(*args, **kwargs)
        if store is not None:
            self.fields['category'].queryset = Category.objects.filter(store=store, is_active=True)
        self.fields['category'].required = False
        self.fields['image'].required = False
        # Empty barcode is auto-generated by the view (the "Avto" button fills
        # it client-side; scanners/typers may skip it entirely).
        self.fields['barcode'].required = False
        # The template hides the cost column from managers; the form must not
        # fail for them - the owner can set the cost later.
        self.fields['base_cost_price'].required = False
        self.fields['low_stock_threshold'].required = False

    def clean_base_cost_price(self):
        value = self.cleaned_data.get('base_cost_price')
        return value if value not in (None, '') else Decimal('0')

    def clean_low_stock_threshold(self):
        value = self.cleaned_data.get('low_stock_threshold')
        return value if value not in (None, '') else 5


class VariantForm(forms.ModelForm):
    """One product variant row (colour × size)."""

    class Meta:
        model = ProductVariant
        fields = ['id', 'color', 'size', 'barcode', 'selling_price', 'cost_price',
                  'stock_quantity', 'low_stock_threshold', 'is_active']
        widgets = {
            'color': forms.Select(attrs={'class': 'select'}),
            'size': forms.Select(attrs={'class': 'select'}),
            'barcode': forms.TextInput(attrs={'class': 'input'}),
            'selling_price': forms.NumberInput(attrs={'class': 'input', 'step': '0.01'}),
            'cost_price': forms.NumberInput(attrs={'class': 'input', 'step': '0.01'}),
            'stock_quantity': forms.NumberInput(attrs={'class': 'input'}),
            'low_stock_threshold': forms.NumberInput(attrs={'class': 'input'}),
        }

    def __init__(self, *args, store=None, product=None, **kwargs):
        super().__init__(*args, **kwargs)
        from apps.products.models import Color, Size
        if store is not None:
            self.fields['color'].queryset = Color.objects.filter(store=store)
            self.fields['size'].queryset = Size.objects.filter(store=store)
        for name in ('color', 'size', 'selling_price', 'cost_price'):
            self.fields[name].required = False
        # Variant barcodes are optional: the view auto-generates them when empty.
        self.fields['barcode'].required = False
        # The variant table has no threshold column; fall back to the model default.
        self.fields['low_stock_threshold'].required = False

    def clean_low_stock_threshold(self):
        value = self.cleaned_data.get('low_stock_threshold')
        return value if value not in (None, '') else 5


class FinanceForm(forms.ModelForm):
    amount = forms.DecimalField(
        min_value=Decimal('0.01'), max_digits=15, decimal_places=2,
        widget=forms.NumberInput(attrs={'class': 'input', 'step': '0.01', 'min': '0'}))

    class Meta:
        model = FinanceEntry
        fields = ['entry_type', 'amount', 'category', 'entry_date', 'comment']
        widgets = {
            'entry_type': forms.Select(attrs={'class': 'select'}),
            'amount': forms.NumberInput(attrs={'class': 'input', 'step': '0.01', 'min': '0'}),
            'category': forms.TextInput(attrs={'class': 'input'}),
            'entry_date': forms.DateInput(attrs={'class': 'input', 'type': 'date'}),
            'comment': forms.Textarea(attrs={'class': 'textarea', 'rows': 2}),
        }


class EmployeeForm(forms.ModelForm):
    pin = forms.CharField(required=False, max_length=8,
                          widget=forms.TextInput(attrs={'class': 'input', 'inputmode': 'numeric',
                                                        'autocomplete': 'off'}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'phone', 'role', 'language', 'is_active']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'input'}),
            'last_name': forms.TextInput(attrs={'class': 'input'}),
            'username': forms.TextInput(attrs={'class': 'input'}),
            'phone': forms.TextInput(attrs={'class': 'input'}),
            'role': forms.Select(attrs={'class': 'select'}),
            'language': forms.Select(attrs={'class': 'select'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['role'].choices = [('manager', 'Manager'), ('cashier', 'Cashier')]
        if self.instance.pk:
            self.fields['username'].disabled = True

    def clean_pin(self):
        pin = self.cleaned_data.get('pin') or ''
        if pin and (not pin.isdigit() or not (4 <= len(pin) <= 8)):
            raise forms.ValidationError('PIN 4-8 raqamdan iborat bo‘lishi kerak.')
        return pin


class StoreSettingsForm(forms.Form):
    """Store-level settings (receipt header/footer, thresholds)."""
    receipt_header = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'textarea', 'rows': 2}))
    receipt_footer = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'textarea', 'rows': 2}))
    low_stock_threshold = forms.IntegerField(min_value=0, widget=forms.NumberInput(attrs={'class': 'input'}))
    phone = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'input'}))
    address = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'textarea', 'rows': 2}))
