# Generated by Django 5.0.4 on 2026-09-30 11:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], db_index=True, max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('entry_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Income / Expense',
                'verbose_name_plural': 'Income / Expenses',
                'db_table': 'finance_entries',
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [models.Index(fields=['entry_type', '-entry_date'], name='finance_ent_entry_t_615e1e_idx')],
            },
        ),
    ]
