# Generated by Django 5.0.4 on 2026-10-01 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('stores', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='financeentry',
            name='finance_ent_entry_t_615e1e_idx',
        ),
        migrations.AddField(
            model_name='financeentry',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stores.store'),
        ),
        migrations.AddIndex(
            model_name='financeentry',
            index=models.Index(fields=['store', 'entry_type', '-entry_date'], name='finance_ent_store_i_ca1fa3_idx'),
        ),
    ]
