# Generated by Django 5.0.4 on 2026-10-01 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_backfill_legacy'),
        ('finance', '0002_remove_financeentry_finance_ent_entry_t_615e1e_idx_and_more'),
        ('stores', '0002_backfill_legacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeentry',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.store'),
        ),
    ]
