# Generated by Django 5.0.4 on 2026-09-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_map_legacy_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pinattempt',
            options={'ordering': ['-created_at'], 'verbose_name': 'PIN attempt', 'verbose_name_plural': 'PIN attempts'},
        ),
    ]
