# Generated by Django 5.0.4 on 2026-10-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_backfill_legacy'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0004_user_store_alter_user_role_and_more'),
        ('stores', '0002_backfill_legacy'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('role', 'platform_admin'), ('store__isnull', True)), models.Q(('role__in', ['owner', 'manager', 'cashier']), ('store__isnull', False)), _connector='OR'), name='user_role_store_context'),
        ),
    ]
