# Generated by Django 5.0.4 on 2026-09-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Stock movement', 'verbose_name_plural': 'Stock movements'},
        ),
        migrations.AlterModelOptions(
            name='stockreceipt',
            options={'ordering': ['-number'], 'verbose_name': 'Stock receipt', 'verbose_name_plural': 'Stock receipts'},
        ),
        migrations.AlterModelOptions(
            name='stockreceiptitem',
            options={'ordering': ['id'], 'verbose_name': 'Stock receipt item', 'verbose_name_plural': 'Stock receipt items'},
        ),
    ]
