# Generated by Django 5.0.4 on 2026-10-01 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stockmovement_options_and_more'),
        ('stores', '__first__'),
        ('vendors', '0002_alter_vendor_options_alter_vendortransaction_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreceipt',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stores.store'),
        ),
        migrations.AlterField(
            model_name='stockreceipt',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name='stockreceipt',
            index=models.Index(fields=['store', '-receipt_date'], name='stock_recei_store_i_f7468c_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockreceipt',
            constraint=models.UniqueConstraint(fields=('store', 'number'), name='stock_receipt_store_number'),
        ),
    ]
