# Generated by Django 5.0.4 on 2026-09-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-generated_at'], 'verbose_name': 'Receipt', 'verbose_name_plural': 'Receipts'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'ordering': ['id'], 'verbose_name': 'Sale item', 'verbose_name_plural': 'Sale items'},
        ),
        migrations.AlterModelOptions(
            name='salereturn',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sale return', 'verbose_name_plural': 'Sale returns'},
        ),
        migrations.AlterModelOptions(
            name='salereturnitem',
            options={'verbose_name': 'Sale return item', 'verbose_name_plural': 'Sale return items'},
        ),
    ]
