# Generated by Django 5.0.4 on 2026-10-01 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_store'),
        ('sales', '0002_alter_receipt_options_alter_sale_options_and_more'),
        ('stores', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sale',
            name='sales_created_7cca36_idx',
        ),
        migrations.AddField(
            model_name='sale',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stores.store'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sale',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['store', 'status', '-created_at'], name='sales_store_i_64c95f_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('store', 'number'), name='sale_store_number'),
        ),
    ]
