# Generated by Django 5.0.4 on 2026-10-01 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_backfill_legacy'),
        ('sales', '0003_remove_sale_sales_created_7cca36_idx_sale_store_and_more'),
        ('stores', '0002_backfill_legacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.store'),
        ),
    ]
